name = "bento-portfolio"
compatibility_date = "2024-12-06"
send_metrics = false
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_flags = ["nodejs_compat"]


[vars]
  NODE_VERSION = "22.12.0"
  PNPM_VERSION = "9"


[dev]
  ip = "127.0.0.1"
  port = 5173
  local_protocol = "http"
